sonar.projectKey=anime-backend
sonar.projectName=anime-backend
sonar.projectVersion=1.0
sonar.sources=src
sonar.host.url=http://localhost:9000
sonar.token=sqp_cbeedda2315457879fea51c0cb044af673d5dbe9
sonar.language=js
sonar.sourceEncoding=UTF-8